Adding custom footer feature for GCIntranet footer
wet-boew/cdts-sgdc pull request #1049
Opened 2023-12-14 19:39 UTC by ahmad-shahid

2023-12-14 21:53 UTC, plup2 requested changes

2023-12-14 21:53 UTC, plup2 commented on test/specs/footer.js
> +        footer: '{"showFeatures": true, "footerPath": "https://esdc.prv/_conf/assets/en/footer/esdcfooter-eng.html", "cdnEnv": "localhost"}',
The tests shouldn't rely on external resources where possible, especially ones that can change without us knowing.

I see two options:
- If we actually have a similar file in the CDTS content, we could have a relative path to it
- OR I'm thinking we could create a folder like `test/html/global` or `test/html/static` or something like that and put the files needed for testing

2023-12-14 21:53 UTC, plup2 commented on test/specs/footer.js
> +    it('Validate custom footer', async () => {
Just a question, the test prior to this one (ie `it('Validate the default footer links'`) , it tests that everything is ok when there is no custom footer, right?  (in other words, we have such a test, right?)

2023-12-19 15:06 UTC, ahmad-shahid commented on test/specs/footer.js
> +        footer: '{"showFeatures": true, "footerPath": "https://esdc.prv/_conf/assets/en/footer/esdcfooter-eng.html", "cdnEnv": "localhost"}',
fixed! pointing to the footer file in the global folder now

2023-12-19 15:06 UTC, ahmad-shahid commented on test/specs/footer.js
> +    it('Validate custom footer', async () => {
Yup, that test checks the links for the default footer

2023-12-19 15:12 UTC, plup2 approved these changes

2023-12-19 15:13 UTC, merged