Removing SSI from samples/appTop
wet-boew/cdts-sgdc pull request #168
Opened 2020-10-06 18:04 UTC by ahmad-shahid

2020-10-06 19:08 UTC, jeanbenoitrochon requested changes
Please have a look at all the "includes" like the following "if ..include" statements, I think we need to add actual html include statement using relative path.

<!--#if expr = "${HTTP_HOST} != localhost" --><!--#include virtual="/app/cls/WET/gcintranet/v4_0_32/cdts/static/appTop-en.html" --><!--#endif-->

2020-10-06 20:42 UTC, shnitze commented
I think the [`_environment.shtml`](https://github.com/wet-boew/cdts-sgdc/blob/Remove-SSI/demo-pages/gcweb/appTop/_environment.shtml) files can also be removed

2020-10-07 13:17 UTC, jeanbenoitrochon approved these changes

2020-10-07 13:17 UTC, ahmad-shahid commented
Removed Environment files

2020-10-07 13:19 UTC, merged