79 replace links that use http
wet-boew/cdts-sgdc pull request #268
Opened 2021-09-23 19:58 UTC by ahmad-shahid

2021-09-24 00:38 UTC, nschonni commented on package.json
> +    "axios": "^0.21.4",
I think these are still devDependencies

2021-09-24 14:19 UTC, plup2 requested changes

2021-09-24 14:19 UTC, plup2 commented on TestLinks.js
> +                        if (!(process.env.DISABLE_PROXY && ((validURL.host).split(".")[1] == "prv" || intranetLinksList.some(intranetLinksList => validURL.href.startsWith(intranetLinksList))))){
Change .split with .endsWith('.prv')

2021-09-24 14:19 UTC, plup2 commented on TestLinks.js
> +    let url = [...new Set(matches)];
Rename `url` to `urls`

2021-09-24 14:19 UTC, plup2 commented on TestLinks.js
> +		throw new Error(errorCount + " error(s) were found when validating URLs.");
Include total number of links checked in error/exception message.

2021-09-24 14:19 UTC, plup2 commented on TestLinks.js
> +}
At the end, add a console.log message sayingsomething like "Done, xxx URLs checked successfully"

2021-09-24 14:19 UTC, plup2 commented on TestLinks.js
> +    async function validateLinks(){
`validateLinks` should take `urls` as a parameter

2021-09-24 14:21 UTC, plup2 commented on package.json
> +    "axios": "^0.21.4",
(I already had started a review and commented on that change, so I resolved this one)

2021-09-27 13:22 UTC, ahmad-shahid commented on src/gcintranet/wet-header.js
> +        return cdnEnv; //if starts with https: return as-is
done

2021-09-27 13:22 UTC, ahmad-shahid commented on package.json
> +  "dependencies": {
done

2021-09-27 13:22 UTC, ahmad-shahid commented on Gruntfile.js
> +            testFileLinks(done);
done

2021-09-27 13:22 UTC, ahmad-shahid commented on TestLinks.js
> +}
done

2021-09-27 13:22 UTC, ahmad-shahid commented on TestLinks.js
> +module.exports = function testFileLinks(done)
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +    validateLinks().then((errorCount) => {if (errorCount !=0){
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +    const fs = require('fs');
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +    let directories = ["./src/", "./public/common/", "./public/gcintranet/", "./public/gcweb/", "./public/global/"];
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +    let exceptionSyntaxList = ["https://www.canada.ca/etc/designs/canada/cdts/gcweb/${definition.themeVersion}",
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +                            "https://nscc-cnas.pwgsc-tpsgc.gc.ca"]
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +    function getFiles (dir, myFiles){
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +    let config = (process.env.DISABLE_PROXY) ? null : {httpsAgent: agent, proxy: false};
done

2021-09-27 13:23 UTC, ahmad-shahid commented on TestLinks.js
> +            if (!exceptionSyntaxList.some(exceptionSyntaxList => url[i].startsWith(exceptionSyntaxList))){
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +                    console.error("HTTP URL Found: " + url[i]);
done for all

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +                        console.error(err);
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +                        if (!(process.env.DISABLE_PROXY && ((validURL.host).split(".")[1] == "prv" || intranetLinksList.some(intranetLinksList => validURL.href.startsWith(intranetLinksList))))){
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +                                if (/4\d[^\D1]/.test(res.status) === true) console.log(validURL.href + "does not have a valid response. Status: " + res.status);
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +    let url = [...new Set(matches)];
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +		throw new Error(errorCount + " error(s) were found when validating URLs.");
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +}
done

2021-09-27 13:24 UTC, ahmad-shahid commented on TestLinks.js
> +    async function validateLinks(){
done

2021-09-27 13:59 UTC, plup2 commented on TestLinks.js
> +                        console.error("Error: An error occured with URL: " + urls[i] + err);
In this message, there will be a missing space ` ` or `: ` delimiter between the url and the error message.

2021-09-27 14:00 UTC, plup2 commented on TestLinks.js
> +	if (errorCount !=0) {
(would not comment on this if it was the only comment but while we're here): Indentation :)  (same for line 6)

2021-09-27 14:20 UTC, ahmad-shahid commented on TestLinks.js
> +                        console.error("Error: An error occured with URL: " + urls[i] + err);
Added a space

2021-09-27 14:21 UTC, ahmad-shahid commented on TestLinks.js
> +	if (errorCount !=0) {
Fixed

2021-09-27 14:29 UTC, plup2 approved these changes

2021-09-27 14:31 UTC, plup2 commented
@ahmad-shahid  All changes are OK but PR is blocked because not all the commits were signed...

2021-09-27 14:49 UTC, merged