Add exitscript object
wet-boew/cdts-sgdc pull request #274
Opened 2021-09-29 20:42 UTC by ahmad-shahid

2021-09-29 21:28 UTC, plup2 requested changes

2021-09-29 21:28 UTC, plup2 commented on src/gcweb/refFooter.ejs
> +        <script data-id="exitScript">cdtsApplyExitScriptToLinks("<%=pr.exitSecureSite.displayModal%>", "<%-pr.exitSecureSite.exitURL%>", "<%=pr.exitSecureSite.exitDomains%>", "<%=pr.exitSecureSite.ex
The statements `param != null? param: 'undefined'` were removed but the `cdtsApplyExitScriptToLinks` function is still expecting undefined values to be `"undefined"` and not `undefined`.   Unless the function itself is modified to change that expectation, all the `?` operations will have to be kept.  (In other words, The difference between the backwards compatible line and this one should only be the addition of `.exitSecureSite` for each parameter.

(same goes for gcintranet file)

2021-10-01 12:42 UTC, ahmad-shahid commented on src/gcweb/refFooter.ejs
> +        <script data-id="exitScript">cdtsApplyExitScriptToLinks("<%=pr.exitSecureSite.displayModal%>", "<%-pr.exitSecureSite.exitURL%>", "<%=pr.exitSecureSite.exitDomains%>", "<%=pr.exitSecureSite.ex
In the exitscript, there is a condition to check if the value is a string and return undefined.
`if (value === "undefined") {
          return undefined;
        }
        return value;`

Would that be ok or do we need to make this change?

2021-10-04 13:33 UTC, plup2 commented on src/gcweb/refFooter.ejs
> +        <script data-id="exitScript">cdtsApplyExitScriptToLinks("<%=pr.exitSecureSite.displayModal%>", "<%-pr.exitSecureSite.exitURL%>", "<%=pr.exitSecureSite.exitDomains%>", "<%=pr.exitSecureSite.ex
That check is fine but only affects the object that will go in the HTML element.

The code still does this:
```javascript
...
    if (targetWarning === "undefined") targetWarning = " ";
...
```

and this 

```javascript
...
if (exitUrl !== "undefined"){
                    links[i].href = encodeURI(exitUrl + (exitUrl.indexOf('?') < 0 ? "?": "&") + "targetUrl=") + encodeURIComponent(links[i].href);
}
...
```

So `"undefined"` (and not `undefined`) still needs to be passed

2021-10-04 14:33 UTC, ahmad-shahid commented on src/gcweb/refFooter.ejs
> +        <script data-id="exitScript">cdtsApplyExitScriptToLinks("<%=pr.exitSecureSite.displayModal%>", "<%-pr.exitSecureSite.exitURL%>", "<%=pr.exitSecureSite.exitDomains%>", "<%=pr.exitSecureSite.ex
That makes sense. It's fixed.

2021-10-04 17:19 UTC, plup2 approved these changes

2021-10-04 17:19 UTC, merged