Fixing accessibility issue on menu bar
wet-boew/cdts-sgdc pull request #327
Opened 2021-11-12 15:21 UTC by ahmad-shahid

2021-11-16 20:53 UTC, plup2 requested changes

2021-11-16 20:53 UTC, plup2 commented on public/gcintranet/ajax/custommenu-eng.html
> +      <li role="presentation"><a href="#" class="item">Menu item 1</a>
As discussed, should it be `role="None"` ?

2021-11-16 20:53 UTC, plup2 commented on public/gcintranet/ajax/custommenu-eng.html
>            <li><a href="#">Menu item 1-1</a></li>
As discussed, `role="None"` as well for submenu items?

2021-11-16 20:53 UTC, plup2 commented on test/specs/appTop.js
> +async function accessibilityExternalMenu(theme, lang) {
We don't need a separate function here, we should change the `accessibility` function to be `async function accessibility(theme, lang, classifier = '')`

2021-11-16 21:22 UTC, nschonni commented on public/gcintranet/ajax/custommenu-eng.html
> +      <li role="presentation"><a href="#" class="item">Menu item 1</a>
https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html

2021-11-17 14:20 UTC, ahmad-shahid commented on public/gcintranet/ajax/custommenu-eng.html
>            <li><a href="#">Menu item 1-1</a></li>
Role has been updated

2021-11-17 14:20 UTC, ahmad-shahid commented on test/specs/appTop.js
> +async function accessibilityExternalMenu(theme, lang) {
done

2021-11-17 14:20 UTC, ahmad-shahid commented on public/gcintranet/ajax/custommenu-eng.html
> +      <li role="presentation"><a href="#" class="item">Menu item 1</a>
Role has been updated

2021-11-17 14:44 UTC, plup2 approved these changes

2021-11-17 14:44 UTC, merged