219 menu item acronym
wet-boew/cdts-sgdc pull request #443
Opened 2022-03-10 19:20 UTC by ahmad-shahid

2022-03-10 19:59 UTC, plup2 requested changes

2022-03-10 19:59 UTC, plup2 commented on src/gcweb/appTop.ejs
> +                                        <a href="#<%=link.id%>" class="item"<%- (link.newWindow==true)? ' target="_blank"  rel="noopener"': '' %>><%_ if (link.acronym != null) { -%><abbr title="<%= l
- Unit test? :) (I guess for both link and sublink)
- Side note: The `acronym` attribute on the Link object is new right?  Corresponding issues should be created in JavaTemplates and DotNetTemplates to add it in SecMenuLink/SecMenuSublink
- Side-side note: Should the changlog mention that menu links now support "acronym" or will that just confuse people?

2022-03-10 19:59 UTC, plup2 commented on src/gcweb/appTop.ejs
> +                                                    <li class="slflnk" role="none"><a href="<%- subLink.subhref %>"<%- (subLink.newWindow==true)? ' target="_blank"  rel="noopener"': '' %>><%_ if (sub
Should be `acronym` instead of `subacronym` .  I know you probably just followed the `subtext`/`subhref` example but naming properties based on the object/class they belong to is is not good :)  (sublink is still a link).  Let's follow the example of `newWindow` instead.

2022-03-14 13:42 UTC, ahmad-shahid commented on src/gcweb/appTop.ejs
> +                                        <a href="#<%=link.id%>" class="item"<%- (link.newWindow==true)? ' target="_blank"  rel="noopener"': '' %>><%_ if (link.acronym != null) { -%><abbr title="<%= l
Added tests, updated changelog, added funnctionality to GCIntranet and updated samples

2022-03-14 13:42 UTC, ahmad-shahid commented on src/gcweb/appTop.ejs
> +                                                    <li class="slflnk" role="none"><a href="<%- subLink.subhref %>"<%- (subLink.newWindow==true)? ' target="_blank"  rel="noopener"': '' %>><%_ if (sub
fixed

2022-03-15 17:36 UTC, plup2 approved these changes

2022-03-15 17:37 UTC, merged