Adding analytics for GCIntranet
wet-boew/cdts-sgdc pull request #451
Opened 2022-03-14 19:50 UTC by ahmad-shahid

2022-03-16 15:12 UTC, plup2 requested changes

2022-03-16 15:12 UTC, plup2 commented on public/gcintranet/samples/adobe-analytics-en.html
> +			canada.ca: https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/[file name]
This is a copy of the gcweb sample right? :)   (paths should say gcintranet)

2022-03-16 15:12 UTC, plup2 commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"cdnEnv": "prod",
(This applies also to gcweb samples)  Is it ok for us to turn it on for real in the sample?  Should we have the webAnalytics parameter commented out?  - Or I guess having this is ok as long as we have `false` in footer?  If removed this would affect the tests we can do.     If it is ok, we totally can keep with `false` is footer

2022-03-16 15:12 UTC, plup2 commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"webAnalytics" : false
(Applies to gcweb samples as well)  
- If answer to previous comment is that yes, it is ok to turn on, should this be false? (if not then it's ok)
- **This parameter is passed in `footer`, but looking at the functions, shouldn't it be `refFooter`?**

2022-03-16 16:06 UTC, ahmad-shahid commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"cdnEnv": "prod",
Oh I generally mixed up this behavior and was thinking setting false in footer would completely turn analytics off but I can't be certain as the script in the head is still rendered. I think we can comment it out for both GCIntranet and GCWeb.

2022-03-16 16:07 UTC, ahmad-shahid commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"webAnalytics" : false
That's strange. Yes it should be in refFooter.

2022-03-17 17:13 UTC, ahmad-shahid commented on public/gcintranet/samples/adobe-analytics-en.html
> +			canada.ca: https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/[file name]
fixed

2022-03-17 17:13 UTC, ahmad-shahid commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"webAnalytics" : false
done

2022-03-17 17:14 UTC, ahmad-shahid commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"cdnEnv": "prod",
done

2022-03-17 20:29 UTC, plup2 requested changes

2022-03-17 20:29 UTC, plup2 commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"cdnEnv": "prod"
As discussed, `/*`

 (also the webAnalytics: true down below)

2022-03-18 13:33 UTC, ahmad-shahid commented on public/gcintranet/samples/adobe-analytics-en.html
> +				"cdnEnv": "prod"
done

2022-03-21 14:18 UTC, merged