Redesigned site footer
wet-boew/cdts-sgdc pull request #689
Opened 2022-12-13 18:53 UTC by ahmad-shahid

2022-12-13 21:12 UTC, plup2 requested changes

2022-12-13 21:12 UTC, plup2 commented on src/gcweb/footer.ejs
> +                        <%_ for (var footerIndex=0; footerIndex<(pr.contextualFooter.link.length > 3 ? 3 : pr.contextualFooter.link.length); footerIndex++) {
Two things here:
- `contextualFooter.link` should be check to make sure it is not null/undefined before doing the for
- `contextualFooter.link` should be named `contextualFooter.links`

2022-12-13 21:12 UTC, plup2 commented on CHANGELOG.md
>  # CDTS Change Log
Also change version in package.json 4.0.47

2022-12-14 14:59 UTC, ahmad-shahid commented on src/gcweb/footer.ejs
> + * @param? contextualFooter Used to determine if the page contextual band will be displayed.
done

2022-12-14 14:59 UTC, ahmad-shahid commented on src/gcweb/footer.ejs
> +                    <h3><%- pr.contextualFooter.title %></h3>
Updated this one and found one other place that required the change.

2022-12-14 15:00 UTC, ahmad-shahid commented on src/gcweb/footer.ejs
> +                        <%_ for (var footerIndex=0; footerIndex<(pr.contextualFooter.link.length > 3 ? 3 : pr.contextualFooter.link.length); footerIndex++) {
done

2022-12-14 15:00 UTC, ahmad-shahid commented on CHANGELOG.md
>  # CDTS Change Log
done

2022-12-14 15:20 UTC, plup2 commented on src/gcweb/footer.ejs
> +    <h2 class="wb-inv">About this site</h2>
This applies here (line 12), line 73 and line 118: Untranslated English text (line 118 used to have translation :) )
**I tried to look carefully, but double-check to make sure I didn't mess any**

2022-12-14 15:43 UTC, ahmad-shahid commented on src/gcweb/footer.ejs
> +    <h2 class="wb-inv">About this site</h2>
done

2022-12-14 17:05 UTC, plup2 approved these changes

2022-12-14 17:05 UTC, merged