Updating custom footer for GCWeb App templates
wet-boew/cdts-sgdc pull request #750
Opened 2023-02-13 15:20 UTC by ahmad-shahid

2023-02-13 15:22 UTC, ahmad-shahid commented
@plup2 Hello, regarding the GCIntranet custom footer, I didn't make any changes. There is code already for backwards compatibility.

Also, it is different than GCWeb because it has sections, rather than just links. I think we should go over it as part of a separate issue as there will be a few things to discuss.

2023-02-13 21:09 UTC, plup2 requested changes

2023-02-13 21:09 UTC, plup2 commented on src/gcweb/appFooter.ejs
> +        <%_ if (pr.footerSections != null) { -%>
This should be just a single `if`

2023-02-13 21:09 UTC, plup2 commented on src/gcweb/appFooter.ejs
> +                    <%_ if (pr.footerSections.title != null) { -%> <h3><%= pr.footerSections.title %></h3> <%_ } -%>
Should check that `pr.footerSections != null && pr.footerSections.title != null`

(and add a test for the "contact link but no footer section situation)

2023-02-13 21:09 UTC, plup2 commented on src/gcweb/appFooter.ejs
> +                <img src="https://wet-boew.github.io/themes-dist/GCWeb/GCWeb/assets/wmms-blk.svg" alt="<^- msg('Symbol of the Government of Canada') ^>">
(*also applies to footer, and wherever else links like this one could have slipped through*)
Link should be to self-hosted image instead.

2023-02-14 13:59 UTC, ahmad-shahid commented on src/gcweb/appFooter.ejs
> +        <%_ if (pr.footerSections != null) { -%>
done

2023-02-14 13:59 UTC, ahmad-shahid commented on src/gcweb/appFooter.ejs
> +                    <%_ if (pr.footerSections.title != null) { -%> <h3><%= pr.footerSections.title %></h3> <%_ } -%>
done

2023-02-14 13:59 UTC, ahmad-shahid commented on src/gcweb/appFooter.ejs
> +                <img src="https://wet-boew.github.io/themes-dist/GCWeb/GCWeb/assets/wmms-blk.svg" alt="<^- msg('Symbol of the Government of Canada') ^>">
done

2023-02-14 14:25 UTC, plup2 approved these changes

2023-02-14 14:25 UTC, merged