Updating terms and privacy links
wet-boew/cdts-sgdc pull request #761
Opened 2023-02-20 18:29 UTC by ahmad-shahid

2023-02-20 18:57 UTC, plup2 requested changes

2023-02-20 18:57 UTC, plup2 commented on src/gcweb/footer.ejs
> +                            <%_ if (Array.isArray(pr.termsLink)) pr.termsLink = pr.termsLink[0] -%>
This change is good but it drops the condition `... && pr.termsLink.length > 0` which could lead to a crash if termsLink is an empty array.   Since `termsLink` property seems to be defaulted below, I think this could be changed to `if (Array.isArray(pr.termsLink)) pr.termsLink = (pr.termsLink.length > 0? pr.termsLink[0]: {};`

(if you see another way of adding the length check back in, feel free)

2023-02-20 18:57 UTC, plup2 commented on src/gcweb/footer.ejs
> +                             <%_ if (Array.isArray(pr.privacyLink)) pr.privacyLink = pr.privacyLink[0] -%>
Same comment as termsLink about dropping the length check

2023-02-20 19:17 UTC, ahmad-shahid commented on src/gcweb/footer.ejs
> +                            <%_ if (Array.isArray(pr.termsLink)) pr.termsLink = pr.termsLink[0] -%>
done

2023-02-20 19:17 UTC, ahmad-shahid commented on src/gcweb/footer.ejs
> +                             <%_ if (Array.isArray(pr.privacyLink)) pr.privacyLink = pr.privacyLink[0] -%>
done

2023-02-21 14:42 UTC, ahmad-shahid commented
Removed the spaces/added semi-colons :)

2023-02-21 15:53 UTC, plup2 approved these changes

2023-02-21 15:53 UTC, merged