Page Feedback Tool
wet-boew/cdts-sgdc pull request #960
Opened 2023-09-22 14:01 UTC by ahmad-shahid

2023-09-22 18:02 UTC, plup2 requested changes

2023-09-22 18:02 UTC, plup2 commented on public/gcweb/samples/feedback-and-share-en.html
> +        "theme": "Text defining the theme of your page",
Instructions say that it should be the same in english and french, our example should probably have both english and french text to be accurate.

2023-09-22 18:02 UTC, plup2 commented on test/specs/preFooter.js
> +        preFooter: '{"showShare": false, "showFeedback": {"enabled": true}, "screenIdentifier": "0123456789", "dateModified": "2020-09-11", "versionIdentifier": "0123456789", "cdnEnv": "localhost"}',
We're changing from false to true, is the intentional/ok?

2023-09-22 18:02 UTC, plup2 commented on test/specs/preFooter.js
> +        preFooter: '{"showShare": ["blogger", "diigo", "email", "facebook", "gmail", "linkedin", "myspace", "pinterest", "reddit", "tinyurl", "tumblr",  "twitter", "whatsapp", "yahoomail"], "showFeed
We're switching from testing with unsupported value to true, is that intentional/ok?

2023-09-22 19:47 UTC, ahmad-shahid commented on CHANGELOG-fr.md
>  # SGDC : Journal des modifications
Updated to 4.2.0. 

Just a side note: I had to update WET because the page feedback tool requires the newer version. We'll probably update WET again whenever we decide to release.

2023-09-22 19:47 UTC, ahmad-shahid commented on CHANGELOG-fr.md
> +- Remplacement du bouton « Signaler un problème » par le nouvel outil de rétroaction sur la page. L'outil de rétroaction sur la page est facultatif et sera masqué à moins qu'il ne soit défini sur vra
done

2023-09-22 19:47 UTC, ahmad-shahid commented on CHANGELOG.md
> +- Replacing the 'Report a problem button' with the new Page Feedback tool. The Page Feedback tool is optional and will be hidden unless it is set to true. Please visit the sample pages for more infor
done

2023-09-22 19:48 UTC, ahmad-shahid commented on public/gcweb/samples/feedback-and-share-en.html
> +            <p><b>Note: </b>Your page needs to have the following metadata: <code>&lt;meta name="dcterms.creator" content="[Department name]"&gt;</code></p>
Done. Moved below the parameter list. I kept the "should" because that is what it says in the WET documentation.

2023-09-22 19:49 UTC, ahmad-shahid commented on src/gcweb/preFooter.ejs
> +    <section class="pagedetails">
After review, that was a mistake on my end! I added back the `container` class but added to the `section` I confirmed on canada.ca

2023-09-22 19:51 UTC, ahmad-shahid commented on src/gcweb/preFooter.ejs
> +            <div class="<%- (pr.showFeedback.enabled != true && pr.showShare != false)? 'col-sm-6 col-md-5 col-lg-4 col-sm-pull-4 col-md-pull-3' : 'col-xs-12' %>">
Yes, so basically there are 4 scenarios and only 1 scenario (if feedback is disabled and share is enabled) has a bunch of classes. All other scenarios just use col-xs-12. 

This is according to the following documentation: https://wet-boew.github.io/GCWeb/sites/page-details/page-details-docs-en.html

2023-09-22 19:51 UTC, ahmad-shahid commented on public/gcweb/samples/feedback-and-share-en.html
> +        "theme": "Text defining the theme of your page",
done

2023-09-22 19:54 UTC, ahmad-shahid commented on test/specs/preFooter.js
> +        preFooter: '{"showShare": false, "showFeedback": {"enabled": true}, "screenIdentifier": "0123456789", "dateModified": "2020-09-11", "versionIdentifier": "0123456789", "cdnEnv": "localhost"}',
Yes so we were testing the default behaviour of the feedback tool (visible) and when it is hidden. 

Since the default behaviour switched, the default page no longer shows the feedback tool. So I switched the behaviour for the 'gcweb-preFooter-en' test file.

2023-09-22 19:55 UTC, ahmad-shahid commented on test/specs/preFooter.js
> +        preFooter: '{"showShare": ["blogger", "diigo", "email", "facebook", "gmail", "linkedin", "myspace", "pinterest", "reddit", "tinyurl", "tumblr",  "twitter", "whatsapp", "yahoomail"], "showFeed
Before, if an url was provided, it would overwrite the 'Report a problem' button url. Since it is no longer supported, I just changed it to be enabled.

2023-09-22 19:57 UTC, ahmad-shahid commented on test/specs/preFooter.js
> +        preFooter: '{"showShare": ["blogger", "diigo", "email", "facebook", "gmail", "linkedin", "myspace", "pinterest", "reddit", "tinyurl", "tumblr",  "twitter", "whatsapp", "yahoomail"], "showFeed
Actually i just realized if a user has a button with an URL, this would become a breaking change. Hmm we'll have to fix this...

2023-09-25 14:49 UTC, ahmad-shahid commented on test/specs/preFooter.js
> +        preFooter: '{"showShare": ["blogger", "diigo", "email", "facebook", "gmail", "linkedin", "myspace", "pinterest", "reddit", "tinyurl", "tumblr",  "twitter", "whatsapp", "yahoomail"], "showFeed
Added back an option of having the legacy feedback button

2023-09-25 18:55 UTC, plup2 requested changes

2023-09-25 18:55 UTC, plup2 commented on CHANGELOG-fr.md
> +- Remplacement du bouton « Signaler un problème » par le nouvel outil de rétroaction sur la page. L'outil de rétroaction sur la page est facultatif et sera masqué à moins qu'il ne soit explicitement
That's probably my bad but:

```suggestion
- Remplacement du bouton « Signaler un problème » par le nouvel outil de rétroaction sur la page. L'outil de rétroaction sur la page est facultatif et sera masqué à moins qu'il ne soit explicitement activé et que d'autres conditions sont remplies. Veuillez visiter les exemples de pages pour plus d’informations.
```

2023-09-25 18:55 UTC, plup2 commented on src/gcweb/preFooter.ejs
> +    if (pr.showFeedback.enabled == true && document.head.querySelector('meta[name="dcterms.creator"]') == null) {
So disabling showFeedback when there is no `meta` is probably not ideal in "legacy url mode".  

Is the `meta` condition ok for all other combination of configuration?

I suggest at the very least:
```suggestion
    if (pr.showFeedback.enabled == true && document.head.querySelector('meta[name="dcterms.creator"]') == null && !pr.showFeedback.legacyBtnUrl) {
```

2023-09-25 19:26 UTC, ahmad-shahid commented on CHANGELOG-fr.md
> +- Remplacement du bouton « Signaler un problème » par le nouvel outil de rétroaction sur la page. L'outil de rétroaction sur la page est facultatif et sera masqué à moins qu'il ne soit explicitement
done

2023-09-25 19:27 UTC, ahmad-shahid commented on src/gcweb/preFooter.ejs
> +    if (pr.showFeedback.enabled == true && document.head.querySelector('meta[name="dcterms.creator"]') == null) {
Fixed. I tested the other combinations. The condition is good.

2023-09-25 21:29 UTC, plup2 approved these changes

2023-09-25 21:29 UTC, merged